default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  username: postgres
  password:
  reconect: true

development:
  <<: *default
  database: dieggotv_dev

test:
  <<: *default
  database: dieggotv_test

production:
  <<: *default
  database: dieggotv
